/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CallbackHashGetter,
  CallbackHashGetterInterface,
} from "../CallbackHashGetter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "getCallbackHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CallbackHashGetter__factory {
  static readonly abi = _abi;
  static createInterface(): CallbackHashGetterInterface {
    return new utils.Interface(_abi) as CallbackHashGetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CallbackHashGetter {
    return new Contract(address, _abi, signerOrProvider) as CallbackHashGetter;
  }
}
