/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CallbackDataGetter,
  CallbackDataGetterInterface,
} from "../CallbackDataGetter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "getCallbackData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CallbackDataGetter__factory {
  static readonly abi = _abi;
  static createInterface(): CallbackDataGetterInterface {
    return new utils.Interface(_abi) as CallbackDataGetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CallbackDataGetter {
    return new Contract(address, _abi, signerOrProvider) as CallbackDataGetter;
  }
}
