/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CheckCalldataValidity,
  CheckCalldataValidityInterface,
} from "../CheckCalldataValidity";

const _abi = [
  {
    inputs: [],
    name: "InvalidCalldata",
    type: "error",
  },
];

export class CheckCalldataValidity__factory {
  static readonly abi = _abi;
  static createInterface(): CheckCalldataValidityInterface {
    return new utils.Interface(_abi) as CheckCalldataValidityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CheckCalldataValidity {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CheckCalldataValidity;
  }
}
