/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEncodeDuration,
  IEncodeDurationInterface,
} from "../IEncodeDuration";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "votingParams",
        type: "bytes",
      },
    ],
    name: "decodeVotingParams",
    outputs: [
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "encodeVotingParams",
    outputs: [
      {
        internalType: "bytes",
        name: "votingParams",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEncodeDuration__factory {
  static readonly abi = _abi;
  static createInterface(): IEncodeDurationInterface {
    return new utils.Interface(_abi) as IEncodeDurationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEncodeDuration {
    return new Contract(address, _abi, signerOrProvider) as IEncodeDuration;
  }
}
