/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEncodeDurationAndTokenweighting,
  IEncodeDurationAndTokenweightingInterface,
} from "../IEncodeDurationAndTokenweighting";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "votingParams",
        type: "bytes",
      },
    ],
    name: "decodeVotingParams",
    outputs: [
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "encodeVotingParams",
    outputs: [
      {
        internalType: "bytes",
        name: "votingParams",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEncodeDurationAndTokenweighting__factory {
  static readonly abi = _abi;
  static createInterface(): IEncodeDurationAndTokenweightingInterface {
    return new utils.Interface(
      _abi
    ) as IEncodeDurationAndTokenweightingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEncodeDurationAndTokenweighting {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEncodeDurationAndTokenweighting;
  }
}
