/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGetCallbackHash,
  IGetCallbackHashInterface,
} from "../IGetCallbackHash";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "getCallbackHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "callbackHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGetCallbackHash__factory {
  static readonly abi = _abi;
  static createInterface(): IGetCallbackHashInterface {
    return new utils.Interface(_abi) as IGetCallbackHashInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGetCallbackHash {
    return new Contract(address, _abi, signerOrProvider) as IGetCallbackHash;
  }
}
