/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGetCallbackData,
  IGetCallbackDataInterface,
} from "../IGetCallbackData";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "getCallbackData",
    outputs: [
      {
        internalType: "bytes",
        name: "callbackData",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGetCallbackData__factory {
  static readonly abi = _abi;
  static createInterface(): IGetCallbackDataInterface {
    return new utils.Interface(_abi) as IGetCallbackDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGetCallbackData {
    return new Contract(address, _abi, signerOrProvider) as IGetCallbackData;
  }
}
