/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ImplementResultFromFingerprint,
  ImplementResultFromFingerprintInterface,
} from "../ImplementResultFromFingerprint";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "ImplementingNotPermitted",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCalldata",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "callbackData",
        type: "bytes",
      },
    ],
    name: "Implemented",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "callbackData",
        type: "bytes",
      },
    ],
    name: "implement",
    outputs: [
      {
        internalType: "enum IImplementResult.Response",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ImplementResultFromFingerprint__factory {
  static readonly abi = _abi;
  static createInterface(): ImplementResultFromFingerprintInterface {
    return new utils.Interface(_abi) as ImplementResultFromFingerprintInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImplementResultFromFingerprint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ImplementResultFromFingerprint;
  }
}
