/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRegistrarPrimitive,
  IRegistrarPrimitiveInterface,
} from "../IRegistrarPrimitive";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "votingContract",
        type: "address",
      },
    ],
    name: "getController",
    outputs: [
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "votingContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "resolver",
        type: "address",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRegistrarPrimitive__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistrarPrimitiveInterface {
    return new utils.Interface(_abi) as IRegistrarPrimitiveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegistrarPrimitive {
    return new Contract(address, _abi, signerOrProvider) as IRegistrarPrimitive;
  }
}
