/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  IsImplementerResolver,
  IsImplementerResolverInterface,
} from "../IsImplementerResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "votingContract",
        type: "address",
      },
    ],
    name: "getIsImplementer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isImplementer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610203806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80635b438c991461003b578063a019ce641461006b575b600080fd5b61005560048036038101906100509190610125565b61009b565b604051610062919061015d565b60405180910390f35b61008560048036038101906100809190610125565b6100f0565b604051610092919061015d565b60405180910390f35b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff169050919050565b60006020528060005260406000206000915054906101000a900460ff1681565b60008135905061011f816101b6565b92915050565b60006020828403121561013757600080fd5b600061014584828501610110565b91505092915050565b6101578161018a565b82525050565b6000602082019050610172600083018461014e565b92915050565b600061018382610196565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6101bf81610178565b81146101ca57600080fd5b5056fea26469706673582212204b53e7dca117de85127b81857c790274469b2327dec083909ca836a88a6aec1564736f6c63430008040033";

export class IsImplementerResolver__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<IsImplementerResolver> {
    return super.deploy(overrides || {}) as Promise<IsImplementerResolver>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IsImplementerResolver {
    return super.attach(address) as IsImplementerResolver;
  }
  connect(signer: Signer): IsImplementerResolver__factory {
    return super.connect(signer) as IsImplementerResolver__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IsImplementerResolverInterface {
    return new utils.Interface(_abi) as IsImplementerResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IsImplementerResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IsImplementerResolver;
  }
}
