/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  IsProxyResolver,
  IsProxyResolverInterface,
} from "../IsProxyResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isProxy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610173806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80632971038814610030575b600080fd5b61004a60048036038101906100459190610095565b610060565b60405161005791906100cd565b60405180910390f35b60006020528060005260406000206000915054906101000a900460ff1681565b60008135905061008f81610126565b92915050565b6000602082840312156100a757600080fd5b60006100b584828501610080565b91505092915050565b6100c7816100fa565b82525050565b60006020820190506100e260008301846100be565b92915050565b60006100f382610106565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b61012f816100e8565b811461013a57600080fd5b5056fea264697066735822122079b4be9314305d0bac1c0e7aa9eaff8dbb6c4e0f3840158d8364b73e42e5762e64736f6c63430008040033";

export class IsProxyResolver__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<IsProxyResolver> {
    return super.deploy(overrides || {}) as Promise<IsProxyResolver>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IsProxyResolver {
    return super.attach(address) as IsProxyResolver;
  }
  connect(signer: Signer): IsProxyResolver__factory {
    return super.connect(signer) as IsProxyResolver__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IsProxyResolverInterface {
    return new utils.Interface(_abi) as IsProxyResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IsProxyResolver {
    return new Contract(address, _abi, signerOrProvider) as IsProxyResolver;
  }
}
