/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  NoDoubleVotingPublic,
  NoDoubleVotingPublicInterface,
} from "../NoDoubleVotingPublic";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "AlreadyVoted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "hasAlreadyVoted",
    outputs: [
      {
        internalType: "bool",
        name: "alreadyVoted",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class NoDoubleVotingPublic__factory {
  static readonly abi = _abi;
  static createInterface(): NoDoubleVotingPublicInterface {
    return new utils.Interface(_abi) as NoDoubleVotingPublicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NoDoubleVotingPublic {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NoDoubleVotingPublic;
  }
}
