/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  NoDoubleVoting,
  NoDoubleVotingInterface,
} from "../NoDoubleVoting";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "AlreadyVoted",
    type: "error",
  },
];

export class NoDoubleVoting__factory {
  static readonly abi = _abi;
  static createInterface(): NoDoubleVotingInterface {
    return new utils.Interface(_abi) as NoDoubleVotingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NoDoubleVoting {
    return new Contract(address, _abi, signerOrProvider) as NoDoubleVoting;
  }
}
