/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { StatusGetter, StatusGetterInterface } from "../StatusGetter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "identifier",
        type: "uint256",
      },
    ],
    name: "getStatus",
    outputs: [
      {
        internalType: "uint256",
        name: "status",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StatusGetter__factory {
  static readonly abi = _abi;
  static createInterface(): StatusGetterInterface {
    return new utils.Interface(_abi) as StatusGetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StatusGetter {
    return new Contract(address, _abi, signerOrProvider) as StatusGetter;
  }
}
