/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IVotingRegistryInterface extends ethers.utils.Interface {
  functions: {
    "changeResolver(address,address)": FunctionFragment;
    "getRegistrar(address)": FunctionFragment;
    "getResolver(address)": FunctionFragment;
    "register(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeResolver",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrar",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getResolver", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export class IVotingRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVotingRegistryInterface;

  functions: {
    changeResolver(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getRegistrar(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<[string] & { registrar: string }>;

    getResolver(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<[string] & { resolver: string }>;

    register(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  changeResolver(
    contractAddress: string,
    resolver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getRegistrar(
    votingContract: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getResolver(
    votingContract: string,
    overrides?: CallOverrides
  ): Promise<string>;

  register(
    contractAddress: string,
    resolver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    changeResolver(
      contractAddress: string,
      resolver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getRegistrar(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getResolver(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<string>;

    register(
      contractAddress: string,
      resolver: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeResolver(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getRegistrar(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResolver(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeResolver(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getRegistrar(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResolver(
      votingContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      contractAddress: string,
      resolver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
